#
# (c) 2018 OpenTHC, Inc.
# This file is part of OpenTHC API released under MIT License
# SPDX-License-Identifier: MIT
#
# OpenTHC API
#

openapi: 3.0.2

info:
  title: OpenTHC API
  description: OpenTHC Data Model and JSON-API reference
  version: "420.20.050"
  contact:
    name: OpenTHC, Inc.
    url: https://openthc.com/
    email: code@openthc.com
  license:
    name: MIT
    url: https://mit-license.org/
  termsOfService: https://openthc.com/about/tos


externalDocs:
  description: "Find out more about OpenTHC"
  url: "https://openthc.com"


#
# Servers
servers:
  - url: https://YOUR_HOST/YOUR/PATH
    description: You can install to sub-host or sub-path
  - url: https://cre.demo.openthc.com
    description: Example Implementation

tags:
  - name: Authentication
    description: Authentication and session management
  - name: System
    description: "Core System Data: Company, License, Contact"
  - name: Config
    description: "Configuration options for each Company/License"
  - name: Crop
    description: "Crop, Plant, Growth and Collection details"
  - name: Inventory
    description: Inventory (Product, Variety, Package) details
  - name: Lab
    description: Details about the Quality Assurance data, Laboratory results
  - name: B2B Transaction
    description: B2B Transactions
  - name: B2C Transaction
    description: B2C Transactions


#
# Componenets
components:
  requestBodies:
    $ref: 'components/request.yaml'
  responses:
    $ref: 'components/response.yaml'
  schemas:
    $ref: 'components/schema.yaml'


#
# Paths
paths:
  $ref: './paths/_.yaml'

#
#models:
#  $ref: './models.yaml'

#  parameters:
#  examples:
# requestBodies:
#   $ref: 'components/request.yaml'
#  headers:
#  securitySchemes:
#  links:
#  callbacks:
#  $ref: './components.yaml'
