#
# (c) 2018 OpenTHC, Inc.
# This file is part of OpenTHC API released under MIT License
# SPDX-License-Identifier: MIT
#
# Product Type object
# @todo mbw
#

description: "Designations for the a Type of a product"
type: object
required: [ "id", "name", "unit" ]
properties:
  id:
    description: ULID or An Internal SKU or Lot ID
    type: string
  name:
    type: string
    description: Name of Product Type
  unit:
    type: object
    properties:
      type:
        type: string
        enum: [ "bulk", "pack", "each" ]
      qty:
        type: number
      uom:
        type: string
        enum: [ "ea", "g", "mg", "ml" ]
  # meta:
  #   type: object
