#
# Product Type object
# @todo mbw
#

type: object
required: [ "id", "name", "unit" ]
properties:
  id:
    type: string
    description: ULID or An Internal SKU or Lot ID
  name:
    type: string
    description: Name of Product Type
  unit:
    type: object
    properties:
      type:
        type: string
        enum: [ "bulk", "pack", "each" ]
      qty:
        type: number
      uom:
        type: string
        enum: [ "ea", "g", "mg", "ml" ]
  # meta:
  #   type: object
