#
# (c) 2018 OpenTHC, Inc.
# This file is part of OpenTHC API released under MIT License
# SPDX-License-Identifier: MIT
#
#
#

post:
  summary: Adjust Inventory
  tags:
   - Inventory
  parameters:
    - name: id
      description: Unique ID value for this Inventory
      in: path
      required: true
      schema:
        type: string
  requestBody:
    description: Inventory Quantity Adjustment Details
    required: true
    content:
      application/x-www-form-urlencoded:
        schema:
          type: object
          required: [ "qty" ]
          properties:
            qty:
              type: number
              description: "The new Quantity of the specified Inventory"
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Inventory'
