#
# (c) 2018 OpenTHC, Inc.
# This file is part of OpenTHC API released under MIT License
# SPDX-License-Identifier: MIT
#


post:
  summary: Combine Multiple Inventory Items to a Single Inventory
  tags:
    - Inventory
  parameters:
    - name: source
      description: Array of Source Inventory Items
      in: formData
      schema:
        type: array
      format: string
      items:
        type: string
    - name: source_weight
      description: Array of Source Inventory Item to Consume
      in: formData
      schema:
        type: array
        format: double
        items:
          type: string
  responses:
    '200':
      description: Success
