#
# (c) 2018 OpenTHC, Inc.
# This file is part of OpenTHC API released under MIT License
# SPDX-License-Identifier: MIT
#
#
#

post:
  summary: Destroy Inventory
  tags:
   - Inventory
  parameters:
    - name: id
      description: Unique ID value for this Inventory
      in: path
      required: true
      schema:
        type: string
  requestBody:
    description: Delete or Destruction details
    required: true
    content:
      application/x-www-form-urlencoded:
        schema:
          type: object
          properties:
            reason_code:
              type: string
              description: "Special Code"
            reason_text:
              type: string
              description: "Why"
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Inventory'
