#
# (c) 2018 OpenTHC, Inc.
# This file is part of OpenTHC API released under MIT License
# SPDX-License-Identifier: MIT
#

get:
  summary: Get a list of Inventory Objects
  tags:
    - Inventory
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Inventory'


post:
  summary: Create, Convert or Split an Inventory object
  tags:
    - Inventory
  requestBody:
    description: Create a new Inventory Inventory
    required: true
    content:
      application/json:
        # schema:
        #   oneOf:
        #     - $ref: '#/components/requestBodies/Request_Create_Inventory'
        #     - $ref: '#/components/requestBodies/Request_Convert_Inventory'
        #     - $ref: '#/components/requestBodies/Request_Split_Inventory'
        examples:
          Request_Create_Inventory:
            summary: Create a Inventory from Scratch
            value:
              source: null
              output:
                product_id: "$PRODUCT_ID"
                variety_id: "$VARIETY_ID"
                qty: 5
          Request_Convert_Inventory:
            summary: Convert to a New Thing
            value:
              source:
                - id: "Inventory_A"
                  qty: 100.00
                - two: "Inventory_B"
                  qty: 23.45
              output:
                product_id: "$PRODUCT_ID"
                qty: 123.45
          Request_Split_Inventory:
            summary: Split an existing Inventory
            value:
              source: "1234567890"
              output: 1234.56
      application/x-www-form-urlencoded:
        schema:
          type: object
          properties:
            source:
              description: Null, String of Single Source, or Array of Source Inventory Items
              type: array
              format: string
              items:
                type: string
            output_product_id:
              description: The Output Product Type
              type: string
            output_qty:
              description: Quantity in Product Type UOMs of the Output
              type: number
              format: float

  responses:
    '201':
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Inventory'
    '400':
      description: Bad Request
