#
# (c) 2018 OpenTHC, Inc.
# This file is part of OpenTHC API released under MIT License
# SPDX-License-Identifier: MIT
#
#
#

get:
  summary: View Inventory Inventory
  tags:
    - Inventory
  parameters:
    - name: id
      description: Unique ULID value for this Inventory
      in: path
      required: true
      schema:
        type: string
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Inventory'

# patch:
#   summary: Modify Inventory Inventory
#   tags:
#     - Inventory

patch:
  summary: Update Inventory Inventory
  tags:
    - Inventory
  parameters:
    - name: id
      description: Unique ID value for this Inventory
      in: path
      required: true
      schema:
        type: string
  requestBody:
    description: Optional Inventory Details
    content:
      application/json:
        schema:
          type: object
          required: [ "product", "variety" , "name" ]
          properties:
            product:
              type: string
              description: "Product ULID ID value"
            variety:
              type: string
              description: "Variety ULID ID value"
            name:
              type: string
              description: "User defined Inventory name"
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Inventory'

#
#
delete:
  summary: Delete the Inventory Inventory
  tags:
    - Inventory
  parameters:
    - name: id
      description: Unique ID value for this Inventory
      in: path
      required: true
      schema:
        type: string
  responses:
    '202':
      description: Marked for Deletion
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Inventory'
    '204':
      description: Success, Delete Confirmed, No Content
