#
# (c) 2018 OpenTHC, Inc.
# This file is part of OpenTHC API released under MIT License
# SPDX-License-Identifier: MIT
#

# Common Components
#

#
# Account Object?
#Account:
#  type: object
#  properties:
#    code:
#      type: string
#      description: Code of the Account, could be a license or business identifier
#    name:
#      type: string
#      description: Name of the Account.

#
Company:
  $ref: './schema/Company.yaml'

#
Company_Type:
  $ref: './schema/Company_Type.yaml'

#
License:
  $ref: './schema/License.yaml'

#
License_Type:
  $ref: './schema/License_Type.yaml'

#
Contact:
  $ref: './schema/Contact.yaml'

#
Contact_Type:
  $ref: './schema/Contact_Type.yaml'

#
Section:
  $ref: './schema/Section.yaml'

#
Variety:
  $ref: './schema/Variety.yaml'

#
Product:
 $ref: './schema/Product.yaml'

#
Product_Type:
  $ref: './schema/Product_Type.yaml'



#
# Plant Object
Plant:
  type: object
  properties:
    id:
      description: Unique Plant Identifier
      type: ulid
    name:
      type: string
      description: Free-form Name of the plant, many times just the Variety
    variety:
      type: object
      $ref: '#/components/schemas/Variety'


#
# Plant_Collect Object
Plant_Collect:
  type: object
  properties:
    id:
      description: Unique Identifier of the Plant Collect operation
      type: ulid
    plant:
      description: Plant Object, may have only "id" property, may be omitted of Plant_Collect is part of a containing Plant
      $ref: '#/components/schemas/Plant'
    type:
      type: string
      enum: [ "raw", "net", "wet-plant", "wet-waste", "dry-buds", "dry-trim", "dry-waste" ]
      description: "Material Type: Flower/Wet, Flower/Dry, Trim/Wet|Dry, Waste/Wet|Dry"
    qty:
      description: Quantity of Material Collected
      type: number
      format: double
    uom:
      type: string
      enum: [ "g", "kg", "oz", "lb" ]
    # plant_list:
    #   type: array

#
# Inventory Object
Lot:
  description: "An Inventory Lot of some Product and Variety"
  type: object
  required: [ "id", "product" ]
  properties:
    id:
      description: The Inventory Unique Identifier
      type: ulid
    name:
      description: Freeform name of the Lot, if desired
      type: string
    product:
      $ref: '#/components/schemas/Product'
    variety:
      $ref: '#/components/schemas/Variety'
    qty:
      description:
      type: number
      format: float


#
#
# Package:
#   type: object
#   properties:
#     qty:
#       type: string
#     uom:
#       type: number



#
Lab_Sample:
  $ref: './schema/Lab_Sample.yaml'

#
Lab_Metric:
  $ref: './schema/Lab_Metric.yaml'

#
Lab_Result:
  $ref: './schema/Lab_Result.yaml'

#
Lab_Result_Metric:
  $ref: './schema/Lab_Result_Metric.yaml'


#
#
B2B_Sale:
  description: "A business to business type of transaction, contains one or more line items."
  type: object
  required: [ "id", "type", "source", "target", "item_list" ]
  properties:
    id:
      description: "ULID"
      type: ulid
    type:
      type: string
      enum: [ "incoming", "outgoing" ]
    source:
      description: "The Source License of the materials, aka: Seller, Sold By"
      type: object
      $ref: '#/components/schemas/License'
    target:
      description: "The Target License of the materials, aka: Buyer, Ship To"
      type: object
      $ref: '#/components/schemas/License'
    depart_at:
      description: Estimate of Departure Time
      type: string
      format: dateTime
    arrive_at:
      description: Estimate of Arrival Time
      type: string
      format: dateTime
    item_list:
      type: array
      items:
        $ref: '#/components/schemas/B2B_Sale_Item'


#
#
B2B_Sale_Item:
  description: "Line item of a B2B Sale"
  type: object
  properties:
    id:
      type: ulid
    lot:
      type: object
      description: Inventory as String ID or Object
    unit_count:
      type: number
      format: double
      description: Quantity of Items Being Transferred
    unit_price:
      type: number
      format: double
      description: The unit price of the item


#
#
B2C_Sale:
  description: "A business to consumer type transaction with one or more line items"
  type: object
  properties:
    id:
      description: The Universal Identifier
      type: ulid
    created_at:
      description: Timestamp of when the Sale was created, which may be different than when the record was created
      type: string
      format: dateTime

B2C_Sale_Item:
  description: "Line item of a B2C Sale"
  type: object
  properties:
    id:
      description: Global/Unique Identifier
      type: ulid
    lot:
      description: Inventory Item Identifier
      type: string
    unit_count:
      description: Quantity of Items Sold
      type: string
    unit_price:
      description: Price per Unit *NOT* the full price
      type: string
