<?php
/**
 * (c) 2018 OpenTHC, Inc.
 * This file is part of OpenTHC API released under MIT License
 * SPDX-License-Identifier: MIT
 */

$this->layout_file = sprintf('%s/view/html.php', APP_ROOT);

?>

<style>
.hero-zero {
	background-image: url("https://cdn.openthc.com/img/s/bg-api.jpg");
}

.hero-zero .hero-mask {
	opacity: 0.80;
}

.fdskjxl {
	margin: 0;
	padding: 2vh 0;
}
</style>

<section class="hero-zero">
	<div class="hero-mask"></div>
	<div class="hero-core">
		<h1>OpenTHC API</h1>
		<h2>A Proposal for Interoperability with a Common Data Model and API</h2>
		<h2><i class="fa-brands fa-github"></i> <a href="https://github.com/openthc/api">github.com/openthc/api</a></h2>
	</div>
</section>

<section class="container mt-4">
<div class="fdskjxl">
	<h2>Regulatory Compliance Data is Complicated and Complex,
		<a href="https://openthc.org/api#why">Closed Systems Are Bad</a>,
		<a href="https://openthc.org/api#interop">Interoperability is Key!</a>
		so we maintain a community driven <a href="https://openthc.org/api#proposal">proposal</a>.</h2>
</div>
</section>


<hr>


<style>
.info-list {
	display: flex;
	flex-direction: row;
	flex-wrap: wrap;
	/* justify-content: space-between; */
	/* list-style-type: none; */
	margin: 0 0 1rem 0;
	padding: 0;
}
.info-list li {
	list-style-type: none;
	margin: 0 0.75rem 0 0 ;
	padding: 0;
}
</style>


<section class="container mt-4" style="font-size: 1.2rem;">

	<h2>Data Models</h2>
	<p>The primary purpose of the OpenTHC API are these <a href="/data-model">common data models</a> which have published <a href="/json-schema">JSON Schema References</a>.</p>

<!--
	<p>There are more than 100 software providers in the cannabis (and general horticulture) space, and just as many data-models and APIs.
		All for the same core data, with just minor differences.
		A common language makes interoperability easier for everyone.
	</p>
-->

	<h3>Examples</h3>
	<p>Here are some examples, and also links to a JSON-schema definition for validation</p>
	<p>These items are defined by YAML in <a href="https://github.com/openthc/api/tree/master/openapi/components/schema">components/schema</a>.</p>
	<ul class="info-list">
		<li><a href="/json-example#company">Company</a></li>
		<li><a href="/json-example#contact">Contact</a></li>
		<li><a href="/json-example#license">License</a></li>
		<li><a href="/json-example#lot">Lot</a></li>
		<li><a href="/json-example#product">Product</a></li>
		<li><a href="/json-example#variety">Variety</a></li>
		<li><a href="/json-example#lab-sample">Lab Sample</a></li>
		<li><a href="/json-example#lab-result">Lab Result</a></li>
		<li><a href="/json-example#b2b">B2B Sale</a></li>
		<li><a href="/json-example#b2c">B2C Sale</a></li>
	</ul>

	<p>The requirement for common &quot;base&quot; or &quot;type&quot; data is handled by collections of YAML files in <code><a href="https://github.com/openthc/api/tree/master/etc">./etc</a></code>.</p>
	<ul class="info-list">
		<li><a href="/base-data#company-type">Company Type</a></li>
		<li><a href="/base-data#license-type">License Type</a></li>
		<li><a href="/base-data#contact-type">Contact Type</a></li>
		<li><a href="/base-data#product-type">Product Type</a></li>
		<li><a href="/base-data#lab-metric-type">Lab Metric Type</a></li>
		<li><a href="/base-data#lab-metric">Lab Metric</a></li>
	</ul>

</section>

<hr>

<section class="container mt-4" style="font-size: 1.2rem;">

	<h2>Documentation</h2>
	<p>
	An <a href="/doc/asciidoctor/" target="_blank" title="OpenTHC API in Asciidoc Format">API manual</a> is available
	<small>(also in <a href="/doc/openthc.pdf" target="_blank" title="OpenTHC API Documentation in PDF generated by Asciidoctor">PDF</a>
	 and <a href="/doc/revealjs/" target="_blank" title="OpenTHC API Documentation using RevealJS">RevealJS</a>)</small>, to describe some of the modeling and the *why* and *when* operations would be executed.
	</p>

	<p>
	It provides details on authentication, plants, inventory, transfers, retail sales and the others details necessary to create robust cannabis applications.
	File a bug if you find any issues.
	</p>

	<p>The OpenAPI documentation has been spun into various formats too:
		<a href="/openapi-ui/dist/?url=/openapi.yaml" target="_blank" title="OpenTHC API in OpenAPI Format">Swagger OpenAPI Reference</a>
		, <a href="/doc/openapi-html/" target="_blank" title="OpenTHC API with OpenAPI HTML Documentation Format">OpenAPI HTML</a>
		, <a href="/doc/openapi-html-v2/" target="_blank" title="OpenTHC API with OpenAPI HTML-v2 Documentation Format">OpenAPI HTML-v2</a>
		, and <a href="/doc/redoc/" target="_blank" title="OpenTHC API in Redoc Format">Redoc</a>
	</p>

</section>

<hr>

<!--
<div class="container mt-4">

<div class="row">
<div class="col-md-6">
	<h2>SDKs</h2>
	<div style="font-size: 1.2rem;">
		<p>These SDKs have been generated via Swagger tools, so they'll all have a common interface.</p>
		<ul>
		<li><a href="/sdk/bash/README.md">bash</a></li>
		<li><a href="/sdk/go/README.md">Go</a> <a href="/sdk/go.zip"><i class="fa-solid fa-download"></i></a></li>
		<li><a href="/sdk/javascript/README.md">Javascript</a></li>
		<li><a href="/sdk/php/SwaggerClient-php/README.md">PHP</a></li>
		<li><a href="/sdk/python/README.md">Python</a></li>
		</ul>
	</div>
</div>

</div>
</div>
-->
